//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipanteEvento
    {
        public int EventoID { get; set; }
        public string Participante { get; set; }
    
        public virtual Eventos Eventos { get; set; }
    }
}
